# Site settings
title: 'Le Roliste qui code'
author: Fabien HIEGEL
description: >
  Mon Espace d'Expression et Expérimentation.
  Artisan logiciel. Code. CV.
  Boîte à outils JdR. Roliste.
# Artisant logiciel, mais roliste avant tout.

# Build Setting
theme: minima

minima:
  social_links:
    twitter: fhiegel
    github: fhiegel
    linkedin: fabien-hiegel-874416b5

# Env Setting
header_pages:
 - index.html
 - cv/index.html
 - cv/nocv/index.md
 - cv/pitch/index.md

collections:
- jobs

# Build
port: 9000

 # Exclude from processing.
 # The following items will not be processed, by default. Create a custom list
 # to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts