# Project information
site_name: Exceller Ensemble
site_url: https://fhiegel.github.io
site_description: >
    Mon espace d'expression, permettant d'apprendre et de partager ma vision de l'Agilité ert du Software Craftsmanship, dans le fun et poure le plaisir.
repo_url: https://github.com/fhiegel/fhiegel.github.io
edit_uri: ""

# Nav

nav:
  - Accueil: index.md
  - Blog:
    - Tous les articles: blog/index.md
    - 2022:
      - blog/2022/05/25/pair-programming--pair-practice.md
      - blog/2022/03/24/codekata--19-ans-aujourdhui.md
      - blog/2022/02/17/cafe-veille-vaisselle.md
      - blog/2022/02/03/la-procrastination.md
      - blog/2022/01/20/design-patterns--factory-method.md
      - blog/2022/01/13/design-patterns--les-gammes-de-la-conception-logicielle.md
      - blog/2022/01/06/retour-du-blog.md
  - Ressources:
    - topics/index.md
    - 🛠️ Sofware Craft:
      - topics/craft/index.md
      - Pair-Programming:
        - topics/pair-programming/index.md
        - Pair-Practice: topics/pair-programming/pair-practice.md
        - Pair-Poetry: topics/pair-programming/pair-poetry.md
        - topics/pair-programming/slides.md
      - La maîtrise personnelle:
        - Katas: topics/katas/index.md
        - topics/katas/lt.md
        - Coding Dojo: topics/coding-dojo/index.md
        - topics/coding-dojo/slides.md
      - TDD: topics/tdd/index.md
      - S.O.L.I.D: topics/solid/index.md
      - Ateliers:
        - Tests Unitaires - Sensibiliser sans coder: topics/sensibiliser-aux-tests-unitaires.md
        - Good Morning Learning: topics/good-morning-learning/index.md
    - 🎓 Veille:
      - topics/veille/index.md
    - 🧩 Gamification:
      - topics/gamification/index.md
      - topics/gamification/lt.md
      - topics/gamification/slides.md
    - En chantier:
      - topics/cold-watching.md

      - topics/design-patterns/index.md
      - topics/design-patterns/gof/index.md
      - topics/design-patterns/gof/factory.md
      - topics/dev-tape/index.md

      - topics/katas/Diamound/index.md
      - topics/katas/FizzBuzz/index.md
      - topics/mob-programming/slides.md
      - topics/solid/deroule.md
      - topics/solid/slides/dip.md
      - topics/solid/slides/intro.md
      - topics/solid/slides/isp.md
      - topics/solid/slides/lsp.md
      - topics/solid/slides/ocp.md
      - topics/solid/slides/srp.md
      - topics/tdd/objectifs-pédagogiques.md
      - topics/tdd/ressources.md
      - topics/tdd/slides.md
      - topics/tdd/vrac.md
      - topics/tdd/triangle-du-developpement/index.md
      - topics/tdd/triangle-du-developpement/slides.md
      - topics/veille/activites.md
      - topics/veille/cfp/veille.md
      - topics/veille/cfp/2022/devoxx.md
      - topics/xtrem/xtrem-reading.md
      - topics/xtrem/xtrem-tech-watch.md
      - topics/xtrem/xtrem-watching.md

  - A propos:
    - Bio: me/bio.md
    - CV: me/cv.md
    - NoCV: me/nocv.md

# Theme options ef2929, d52929

# Configuration

theme:
  name: material
  custom_dir: theme
  language: fr
  logo: assets/images/icon-128x128.png
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    # - navigation.indexes
  palette:
    primary: black
    accent: red

# Extra
extra_css:
  - assets/css/extra.css

extra:
  author:
    name: fhiegel
    icon: fontawesome/solid/blog
    link: https://fhiegel.github.io
    #  https://github.com/squidfunk/mkdocs-material/tree/master/material/.icons/
    #  icon: /fontawesome/solid/blog
    #  icon: fontawesome/solid/arrow-alt-circle-up
    #  icon: fontawesome/solid/angle-left
    #  icon: fontawesome/regular/lemon
    #  icon: fontawesome/regular/id-badge
    #  icon: fontawesome/solid/dice-d20
  reveal:
    path: reveal.js/dist
    transition: slide
    theme:
      name: white.css
      path: theme
    plugin:
      path: reveal.js/plugin
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fhiegel
      name: fhiegel on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fhiegel
      name: fhiegel on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fabien-hiegel-874416b5
      name: Fabien Hiegel on LinkedIn

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml

plugins:
  - search
  - redirects:
      redirect_maps:
        'learn/presentations/good-morning-learning/': 'topics/good-morning-learning/index.md'
        'learn/presentations/good-morning-learning/slides/': 'topics/good-morning-learning/slides/index.md'
        'learn/presentations/good-morning-learning/slides/en.md': 'topics/good-morning-learning/slides/en.md'
