name: 🔧  Build and Deploy on GitHub Pages 🚀

on:
  push:
    branches:
      - docs

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: 🔧 Build Documentation 📖
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install and Build 🔧
        run: |
          pip install -r theme/requirements.txt 
          mkdocs build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
  deploy:
    name: 🚀 Deploy Documentation 📖
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v4